### ISSUE TITLE
UCP nav menu - issue with the icon

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Isango#110]
![image](https://user-images.githubusercontent.com/778890/105643702-a5364c00-5e91-11eb-9d7d-3a2e0d43ca59.png)

**Comment by effone** [comment]
`background-repeat: no-repeat;` will help.

**Comment by Eldenroot** [comment]
Maybe we should move to single category, would be better? Or do you prefer leave it in "Your profile" section?

**Comment by effone** [comment]
Its related to profile only.

**Comment by Eldenroot** [comment]
OK, I agree!
