### ISSUE TITLE
Buttons are not parsed in templates (theme)

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Isango#135]
{$isango_buttons},{$isango_input['min']}, {$isango_input['max']}, {$isango_input['pop']}

Are not parsed... only works in UCP.

@effone

**Comment by effone** [comment]
They are global

**Comment by Eldenroot** [comment]
Nope, I can reproduce on my board. I use my own buttons so I didn't catch it sooner... anyway it as fine with pre-release of 2.0.0. I think it is valid, I have tried on the board from the user who reported on MyBB board.

**Comment by Eldenroot** [comment]
@effone - more info:

- in register page: works fine 
![image](https://user-images.githubusercontent.com/778890/107695008-51f53380-6cb0-11eb-947d-9b8fb65ae3be.png)
- in UCP - connections - works fine
- in modal login window - not working
- in header - not working
anywhere else on index - not working

This is quite a critical issue :(
