### ISSUE TITLE
GitHub error

### ISSUE THREAD

**Issue by GreywaterSoftware** [mybbgroup/Isango#147]
I don't now if my OAuth App is set up correctly, but whenever someone tries signing up with GitHub, it doesn't registrar them and throws an error saying `"Service 'GitHub' failed to return acceptable 'Email'. Check your account settings or try different service gateway."`

**Comment by effone** [comment]
Set email ID of github publicly available.
The person trying to log in using github has his email as private.

**Comment by GreywaterSoftware** [comment]
Perfect thank you!
