### ISSUE TITLE
Different size of buttons

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Isango#22]
Make a setting to choose between 2 size of buttons - icons only and icon with text (already done).

**Comment by effone** [comment]
Or a compact dropdown menu to choose from?
Can be UI improved with a tiny self-coded jquery plugin as well ...

**Comment by Eldenroot** [comment]
It depends... first of all I would like to see main core features and then we can handle this. CSS part is simple, I am not a jQuery guy so I am free to discuss it :)
