### ISSUE TITLE
Allow connection without email

### ISSUE THREAD

**Issue by effone** [mybbgroup/Isango#33]
Allow users to connect services that doesn't return email address. Enable users to login using ID only in that case.

Note: Need to evaluate if registration is possible without email address (and force user to provide email after registration?)

**Comment by Eldenroot** [comment]
Quite tricky - only security way is to verify the email after registration

**Comment by Eldenroot** [comment]
I am not sure about this one, because mybb needs emails for registration, do we really wanna add this?

**Comment by effone** [comment]
No we don't. At least not now.
