### ISSUE TITLE
Bump Plugin Version + Code Formatting

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Isango#36]
https://github.com/mybbgroup/Isango/blob/263fc9140178efda3438266df54d1eb1ee9a04e6/upload/inc/plugins/isango.php#L22

As title says we have to bump version number in next release (for now let it be).

**Comment by effone** [comment]
Oopz...

**Comment by effone** [comment]
Closed by #57

**Comment by effone** [comment]
Need to bump to **2.0.0**
