### ISSUE TITLE
SCSS and MAP files for CSS compilation

### ISSUE THREAD

**Issue by yuliu** [mybbgroup/Isango#37]
It seems that SCSS and MAP are for generating the actual CSS file. If so, it might not be included in release build.

I'm not familiar with how to use those SCSS and MAP files. Could anyone write a little more on development of Isango with an appropriate way of handling the CSS file on the README page or in the Wiki section?

Thanks.

**Comment by effone** [comment]
You have a point there but I have included SCSS files for easily modifying and generating relative CSS for those who really knows SCSS.
Map files have no end user use but if it is there the actual location in an SCSS file can be identified by inspection in place of generated CSS.
Will consider omitting inclusion of those development files in future release. Thanks for heads up.
