### ISSUE TITLE
Duplicate `add_breadcrumb` in UserCP

### ISSUE THREAD

**Issue by yuliu** [mybbgroup/Isango#38]
The following code has outputted a nav link to UserCP in `usercp.php`:
```
add_breadcrumb($lang->nav_usercp, "usercp.php");
```

Isango has done it again in `isango_connections()`. I don't know if it's required, but the navigation will show two identical links to UserCP.

**Comment by effone** [comment]
:/ can't find any dupe
Steps?

**Comment by yuliu** [comment]
Some pages will show, like `/usercp.php?action=options`. I will submit a PR soon.

A second thought, it can also be viewed as MyBB's `add_breadcrumb()` is too far behind running hook. But it might depend whether add_breadcrumb before calling hooks is good.

**Comment by effone** [comment]
You are right.
Thanks for the PR.
