### ISSUE TITLE
No idea where the callback URL is.

### ISSUE THREAD

**Issue by stampylongr** [mybbgroup/Isango#40]
Yeah,
I am stupid, and I cannot figure out the callback URL for the life of me.
Please send help!

**Comment by effone** [comment]
For all gateways it is:
`http(s)://{$your_site}/member.php?action=login&gateway={$gateway}`

For example, if your site is `stampy.com` and you are making app for google, the redirect url you have to set is:
`https://stampy.com/member.php?action=login&gateway=google`

For those providers who don't allow fragmented callback url, just set:
`https://stampy.com/member.php`
... and it will all work good.

Sorry for poor documentation. Will improve adding some wiki pages managing time.
