### ISSUE TITLE
Possible problem with other required fields

### ISSUE THREAD

**Issue by MinusPL** [mybbgroup/Isango#43]
I've noticed that if some fields of profile are required but cannot be provided by gateway it will fail to register new account. Also fields like gender if are hidden on gateway it will fail to register new account. Maybe consider allowing then people to fill missing fields on some kind of "stripped" registration form or just simply load default values provided and allow account to be created.

**Comment by Eldenroot** [comment]
What about just skip these required fields if user is registered via 3rd party... because many 3rd party services does not provide these data (or it is really limited). I think this is quite a high priority ticket - especially for boards where any profile field is required in registration process. @effone @lairdshaw

**Comment by effone** [comment]
This is very awkward condition while there might not be any possible default value against a set required field.
Will explore possibilities to bypass required field check or may end up asking from the user only before creating the account...

**Comment by Eldenroot** [comment]
Yeah, is there any usable hook?

**Comment by effone** [comment]
I am afraid there is no hook as such.

But there is one hack available. Admin CP has inbuilt bypass ability. So, if we define `IN_ADMINCP` the check gets bypassed. Don't know if this is acceptable or not.

**Comment by effone** [comment]
Like to have opinion of @lairdshaw on this.

**Comment by Eldenroot** [comment]
@lairdshaw - what do you think?

@effone - I think it is quite necessary for boards where some profile fields are required. Btw MyFacebook connect from Shade works fine even when you have some fields required during the registration. If you register via MyFacebook connect plugin, the field is empty but registration is done without any issue.

**Comment by lairdshaw** [comment]
@effone, @Eldenroot, I reckon that ideally we'd do as @effone suggested: present to the user a minimal registration form with the missing required fields.

The IN_ADMINCP hack is another possibility, and here's yet another (untested code; just to get the idea across):

Just before [line 384](https://github.com/mybbgroup/Isango/blob/7e084af099617c5b7b62f97c01529a1fd38c2ccf/upload/inc/plugins/isango.php#L384) of `inc/plugins/isango.php`, insert the following:

```php
// Temporarily set all required profile fields to not
// required, keeping a list of those fields so we can
// restore them afterwards.
$req_fields = array();
global $cache;
$pfcache = $cache->read('profilefields');
if (is_array($pfcache)) {
	foreach ($pfcache as $id => $profilefield) {
		if ($profilefield['required'] == 1) {
			$req_fields[$id] = $profilefield;
			$profilefield['required'] = 0;
		}
	}
}
$cache->write('profilefields, $pfcache);
```

And then immediately after line 386, to insert this code (although we'd also want to make sure it gets run in the event that `$userhandler->validate_user()` returns false):

```php
// Restore required profile fields
foreach ($req_fields as $id => $profilefield) {
	$profilefield['required'] = 1;
	$pfcache[$id] = $profilefield;
}
$cache->write('profilefields, $pfcache);
```

**Comment by effone** [comment]
Shade did this with FacebookConnect:
```php
        unset ($data->errors['missing_required_profile_field'],
               $data->errors['bad_profile_field_values'],
               $data->errors['max_limit_reached']);
```
Not bad idea, but I also like @lairdshaw 's approach.

**Comment by lairdshaw** [comment]
Yes, Shade's approach is simpler and perhaps more elegant than mine - as well as less prone to accidentally leaving the `profilefields` cache with incorrect contents.
