### ISSUE TITLE
Disable login with non-connected services.

### ISSUE THREAD

**Issue by Sama34** [mybbgroup/Isango#45]
Hi. I would like users to login using only connected services. That is, for users to be able to login use a service they would need to connect from the UCP first.

A option to do this would be awesome.

**Comment by effone** [comment]
As I evaluate this is same as #44 created by you.
Basically disabling new account creation will depend login only with connected services.

**Comment by Sama34** [comment]
Yes, it is basically the same request. I probably missed or clicked twice too quick.
