### ISSUE TITLE
No option to add Terms/Privacy links

### ISSUE THREAD

**Issue by nickhanson232** [mybbgroup/Isango#53]
As per googles developer policies I am trying to configure the plugin to display TERMS and Conditions/Privacy Policy links.

The plugin does not give any customization for such thing.

Possible for such feature to be implemented in next update?

**Comment by nickhanson232** [comment]
The Google Trust & Safety team mentioned that I must provide the following:

Google Sign-in
•	Make sure the Google sign-in button on your project’s homepage  https://forum.hgnetwork.net/index.php follows the Google sign-in branding guidelines. https://developers.google.com/identity/branding-guidelines#top_of_page

**Comment by Eldenroot** [comment]
@effone - maybe we should add this, because not only Google requires this :( 

Any basic common accept terms/privacy page after registration for the first time would be enough?

**Comment by effone** [comment]
Being a multi-login system it is not possible to add every Service's TOS below the plugin.
This plugin provides basic integration. Any user can modify the button using any of his own choice / supplied by the provider and the plugin will work fine as long as it provides the right gateway in url.

For example, this can be added anywhere in the template and will work for Google seamless:
`<a class="button" href="member.php?action=login&gateway=google">Login with Google</a>`
