### ISSUE TITLE
Issues with discord registration

### ISSUE THREAD

**Issue by IamAiDN** [mybbgroup/Isango#54]
When attempting to sign up using discord I'm given the following error message: 

"Failed to receive token data from 'Discord' (status code: 0). Please contact Administrator."

I believe i've done the setup correctly as I have both of the 0auth links on my discord developer panel and I have the 2 needed ID's in my forum ACP menu.

**Comment by Eldenroot** [comment]
@effone - not possible to reproduce here, any clue?

**Comment by effone** [comment]
This is explanatory.
Its a misconfiguration of Discord App creation which results non receipt of token data.
Tested 3 different sites, incl. [MyBB Group site](https://mybb.group) - Discord is up and functional.

Need some times to write a [Wiki](https://github.com/mybbgroup/Isango/wiki) page about setting up app for Discord.
