### ISSUE TITLE
Delete Confirmation Message

### ISSUE THREAD

**Issue by effone** [mybbgroup/Isango#69]
Implement delete confirmation message in UCP before attempting deletion of connection.

**Comment by Eldenroot** [comment]
What if a user will delete all connections, is that possible? It should be, because email is loaded on registration and saved to mybb, password will be generated (or a user can reset the password which will be send on the mail).

**Comment by effone** [comment]
It is very much possible.
On new registration 2 separate entries get created:
1. User data for user account in `user` table
2. Connection data in `isango` table

If a user deletes all connections; still the account remains.
There is already a function in place to delete all connections at once which runs on user account deletion. We can simply reuse that function for this.

**Comment by Eldenroot** [comment]
Great, would be nice to add if it is not too difficult and time consuming.
