### ISSUE TITLE
Discord login concerns

### ISSUE THREAD

**Issue by cjeje84** [mybbgroup/Isango#74]
Hello I have the following problem when I want to login with discord thank you in advance for your help

invalid oauth2 redirect_uri

**Comment by effone** [comment]
This is the working redirect URI of our group site.
Just change to your domain and try as the rest of the URL is:

![](https://i.ibb.co/qY0ntzf/image-2021-01-13-144820.png)

**Comment by cjeje84** [comment]
Thank you

**Comment by effone** [comment]
Considering its resolved.
You can further use our [group site thread](https://mybb.group/Thread-Isango) for seeking support instead of using Github issues:
https://mybb.group/Thread-Isango
