### ISSUE TITLE
Name/nickname sync on registration step

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Isango#80]
As discussed here #55 the support for sync username instead of email should be added (if the gateway supports it):

- [ ] Wordpress
- [ ]  Discord
- [ ]  Facebook
- [ ]  Google
- [ ]  Spotify
- [ ]  GitHub
- [ ]  LinkedIn
- [ ]  Yahoo
- [ ]  Yandex
- [ ]  Vkontakte - not support by Isango (check PR #66 )
- [ ]  Microsoft

We will keep the list updated according to the actual support and added gateways in Isango.

**Notes:**
- sync username only in registration step, not in other login
- if more providers are linked to the account, we should sync only the first one, others will be skipped

**Comment by effone** [comment]
Isango is already syncing available username with the newly created account. If the username is not available then it tries to generate best possible / available username based on available data:
https://github.com/mybbgroup/Isango/blob/master/upload/inc/plugins/isango.php#L343

An option is already discussed to prompt the user to ender an username of his choice:
https://github.com/mybbgroup/Isango/issues/19

So, is this issue still valid?

**Comment by Eldenroot** [comment]
Maybe #19 is valid and could solve the issue with usernames... what do you think? Feel free to close this one.

**Comment by effone** [comment]
Yes. 19 is valid and milestoned.
There is a comment in the plugin for a rare situation when no username is possible to be decided. We need user input in that scenario anyway.
https://github.com/mybbgroup/Isango/blob/master/upload/inc/plugins/isango.php#L356-L357
