### ISSUE TITLE
Usergroup after registration via 3rd party providers

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Isango#92]
Would be nice to have this option:

![image](https://user-images.githubusercontent.com/778890/105411749-12e53c80-5c34-11eb-9475-9cec578b8a6d.png)

**Comment by effone** [comment]
Are you referring the second one in the snap?
Coz first one is already in place...

**Comment by Eldenroot** [comment]
Yes, just an idea to discuss. Thats why I havent added any labels etc.

**Comment by effone** [comment]
I am not sure how it can be handled for multiple gateways.
The snap in issue handles only facebook.
