### ISSUE TITLE
Disable classic MyBB registration system, force users to register/login via 3rd party providers

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Isango#93]
Something like this but global for all services in Isango.

![image](https://user-images.githubusercontent.com/778890/105411841-33ad9200-5c34-11eb-876b-bf1e7df52363.png)

**Comment by effone** [comment]
For Isango, currently it is always forced.
To disable registration completely you need to disable registration by Isango from Isango settings as well.
